### ISSUE TITLE
Turn on CI?

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf-spec#36]
Should we consider turning on CI on this repository, and running these specs against the current develop branch? Obviously, they would sometimes fail, but at least we could let the failures show in Travis and make an educated decision.

**Comment by gkellogg** [comment]
Currently, running spec in rdf-spec isn't very informative. Perhaps there's something that can be done in .travis.yml to run tests from RDF.rb; is that what you had in mind? Otherwise, it might mean creating copies of the specs from RDF.rb in rdf-spec/specs that do much the same thing.

**Comment by no-reply** [comment]
> Currently, running spec in rdf-spec isn't very informative. Perhaps there's something that can be done in .travis.yml to run tests from RDF.rb; is that what you had in mind?
